### ISSUE TITLE
Грамматика предлагаемого языка не разрешает переменные внутри выражений, что противоречит примерам

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#33]
Предполагаю, что должно быть не так:

    EXPRESSION = FUNCTION_CALL | BINARY_EXPRESSION | LITERAL | "(" EXPRESSION ")"

а так:

    EXPRESSION = FUNCTION_CALL | BINARY_EXPRESSION | LITERAL | IDENTIFIER | "(" EXPRESSION ")"

@dzharkov , верно ли это?

**Comment by dzharkov** [comment]
Согласен, это бага в грамматике
Сейчас залью обновление
