### ISSUE TITLE
Грамматика предлагаемого языка требует фигурные скобки вокруг тела if, что противоречит примерам

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#34]
Полагаю, что `BLOCK_WITH_BRACES` вообще не нужно нигде, кроме `FUNCTION` (а раз так, то я бы от него вообще избавился).
В теле `IF` и `WHILE`, полагаю, нужно `BLOCK | BLOCK_WITH_BRACES`. Правда, тогда нужно отдельно обговорить, к чему цепляется `else` в случае `if (a) if (b) c() else d()`

@dzharkov Какая интерпретация условия верная?

Ещё идея: я бы сказал, что `BLOCK` — это либо фигурные скобки с блоком внутри, либо последовательность команд.

**Comment by yeputons** [comment]
Прошу прощения, предложил некоторую чушь.
Предлагаю изменить грамматику по сравнению следующим образом:
1. Добавить в `STATEMENT` случай `BLOCK_WITH_BRACES`.
2. В телах `IF` и `WHILE` требовать `STATEMENT`, а не `BLOCK_WITH_BRACES`.

**Comment by dzharkov** [comment]
В принципе так и задумано, что в if/while требуются фигурные скобки.
Но я не против, если в твоем парсере будет так, как описано выше

**Comment by yeputons** [comment]
@dzharkov Если так и задумано, то стоит поправить примеры — в них сейчас, например, есть строчка `if (n <= 1) return 1`

**Comment by dzharkov** [comment]
Согласен, поправлю
