### ISSUE TITLE
Как писать юнит-тесты парсера для Antlr?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#35]
@dzharkov 

Самым разумным кажется примерно следующее:

1. Выбираем правило и пишем строчку, которая этим правилом должна разбираться.
2. В тесте запускаем парсер и получаем разобранный `*Context`
3. Сравниваем этот `Context` с эталонным.

В пункте 3 возникает проблема: сравнивать можно лишь методом "аккуратно прошлись по всем детям и убедились, чему они равны". Это как-то не очень выглядит.

Альтернатива: создать свои `data class` для представления AST, сконструировать их в парсере и потом уже сравнивать при помощи обычного `==`.

Что стоит выбрать?

**Comment by dzharkov** [comment]
Мне больше всего нравится вариант со своим AST, но про то, чтобы делать его `data` -- вопрос спорный, потому что дерево разбора -- довольно сложный объект.
Я бы определил свой компаратор, либо сделал стабильный принтер дерева и в качестве эталона сравнивал со строкой
