### ISSUE TITLE
IDEA не (пере)собирает ANTLR-файлы самостоятельно после импорта gradle-проекта

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#36]
Как воспроизвести на ветке `antlr-example` в IDEA 2017.2.5:

1. Берём чистый, только что склонированный репозиторий.
2. Import project from Gradle, включаем авто-импорт.
3. Нажимаем Ctrl+F9, чтобы собрать проект.
4. Получаем ошибку "`ru.spbau.mit.parser.ExpLexer` not found.

Кажется, что при импорте теряется информация о том, что до сборки Java/Kotlin-файлов надо ещё запустить Antlr, gradle при этом работает корректно.

У меня не получилось заставить IDEA пересобирать, поэтому я [попросил её собирать всё через gradle, а не самостоятельно](https://www.jetbrains.com/help/idea/gradle.html#delegate_build_gradle). Мне кажется, это было бы полезно добавить в описание задания, потому что это раздражающая и опасная особенность (можно не пересобрать изменённую грамматику).

@dzharkov

**Comment by yeputons** [comment]
Хм, при этом, правда, теряется нафиг всё отображение ошибок в нижней панели. Печальненько.

**Comment by yeputons** [comment]
Нашёл только один способ пересобирать что-то из IDEA: поставить [плагин](https://github.com/antlr/intellij-plugin-v4). К сожалению, он не умеет добавляться в команду "Build Project" и умеет только собирать при сохранении (если галочку поставить). Так что, видимо, пока что буду страдать с пересборкой грамматики при помощи явного запуска цели gradle `generateGrammarSource`.

**Comment by dzharkov** [comment]
Конечно, IDEA поддерживает только стандартные билд таски. Если честно, не очень понятно, как в принципе можно было бы поддержать произвольные билд конфигурации.

С моей точки зрения вариант с ручным запуском таски (либо delegate build to gradle) не то, чтобы очень плохой.
У нас в проекте по умолчанию delegate build to gradle, например.

**Comment by yeputons** [comment]
Но ведь тогда вообще не видны ошибки сборки?

**Comment by dzharkov** [comment]
Видны во вкладке `Build`, просто весь гредловый stdout
