### ISSUE TITLE
Какова семантика переопределения переменных при выходе из блока?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#37]
Пример кода:

```
var x = 1
if (1) {
  var x = 2;
}
println(x);
```

Возможный вывод:
1. `1`, если предположить, что внутренний `x` лишь скрывает (shadows) внешний.
2. `2`, если предположить, что внутренний `x` просто переопределяет значение внешнего.
3. `2`, если предположить, что внутренний `x` целиком заменяет собой внешний и продолжает жить после конца scope.
4. Runtime error, если предположить, что внутренний `x` целиком заменяет собой внешний, но умирает после конца scope.

С точки зрения C ответ был бы "1". В других языках может быть по-другому (например, в JavaScript переменные создаются только в начале функции),

**Comment by yeputons** [comment]
P.S. Верно ли, что переменная тоже не видна за пределами блока, где она объявлена?

@dzharkov

**Comment by dzharkov** [comment]
Да, первый вариант. И да, не видна за пределами блока
