### ISSUE TITLE
Какова семантика замыканий?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#38]
Третий пример демонстрирует, что в нашем языке в каком-то смысле есть замыкания:

```
fun foo(n) {
    fun bar(m) {
        return m + n
    }

    return bar(1)
}

println(foo(41)) // prints 42
```

Я могу интерпретировать это несколькими способами:

1. В момент создания функции `bar` внутри `foo` она запоминает _значения_ всех переменных, который на этот момент были в текущем scope.
2. В момент создания функии `bar` внутри `foo` она запоминает _ссылки_ на все переменные, которые были в текущем scope.
3. В момент _вызова_ функции `bar` она находит переменную с именем `n` в каком-нибудь из фреймов вверх по стеку.

@dzharkov , вопрос: какова семантика замыканий?

Например, пункты 1 и 2 можно отличить, если добавить внутри `foo` команду `n = n + 1`. А пункт 3 от них можно отличить таким примером:

```
fun foo() {
  println(n)
}
var n = 10
foo()  // prints 10
```

Бонусный вопрос: что происходит при записи в переменную, которая объявлена не в текущем блоке? Например, Python трактует глобальные и локальные переменные по-разному (из-за того, что в нём нет команды объявления): из глобальных по умолчанию можно только читать, а чтобы в них писать, надо написать `global some_var`.

**Comment by dzharkov** [comment]
Не возражаю против второго или третьего варианта.
Глобальный переменные почти никак не отличаются от локальных
