### ISSUE TITLE
Требуется ли поддержка взаимной рекурсии?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#46]
Продолжение вопроса про замыкания (#38): если предполагать, что правила видимости для функций совпадают с правилами видимости для переменных, то при выборе семантики "функция захватывает переменные и функции в момент создания" получается невозможно сделать взаимную рекурсию:

```
var x
fun foo() {  // Захватывает только x и foo
  bar();  // Функция bar() объявлена ниже, поэтому её не видно
}
fun bar() {  // Захватывает x, foo и bar
  foo();  // ОК
}
```

Способы решения:
1. Автоматически объявить все функции и переменные в начале блока (почти как в JavaScript).
2. Считать, что функция при объявлении захватывает родительский scope по ссылке, а не все отдельные переменные по ссылке. Тогда между объявлениями `foo` и `bar` всё ещё нельзя будет вызвать `foo()` (потому что `bar` не объявлена), но потом будет можно. Кажется, так сделано в Python.
3. Сказать, что замыканий в языке нет и на самом деле поиск функций и переменных происходит только в момент вызова (см. опцию 3 из #38)
4. Не разрешать взаимную рекурсию.
@dzharkov

**Comment by yeputons** [comment]
Обращаю внимание, что в языке C++, например, выбрали способ 4. Да и [в Kotlin тоже](https://discuss.kotlinlang.org/t/problem-with-mutual-recursive-local-functions/2480), там даже обычная рекурсия для анонимных лямбд вроде бы [не поддерживается](https://youtrack.jetbrains.com/issue/KT-10350). Взаимная рекурсия дозволяется только на уровне методов и, вероятно, глобальных функций, но в нашем мини-языке такого различия нет.

**Comment by yeputons** [comment]
Я выбрал способ 4.

**Comment by dzharkov** [comment]
В принципе 4 вариант норм
