### ISSUE TITLE
Можно ли как-то поддержать параметры и вида `key=value` и просто `option`?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#65]
В техе бывают как просто дополнительные параметры, так и параметры со значениями, например:

`\includegraphics[width=0.8\textwidth,height=0.8\textheight,keepaspectratio]{foo}`

Вероятно, эту штуку можно было бы закодировать как-то так:

`includegraphics("width" to "0.8", "height" to "0.8", "keepaspectratio", "foo")`

Но, увы, `vararg` требует, чтобы все элементы этого типа были одинаковые, а мне хочется, чтобы можно было передавать либо `String`, либо `Pair<String, String>`. Можно ли это сделать?

@dzharkov 

Две идеи:

1. Получать `vararg` типа `Any` и разбираться в runtime. Как-то не очень.
2. Передавать параметры без значения как `"foo" to null`. Можно даже завести extension function, который будет это делать.

**Comment by dovchinnikov** [comment]
```
includegraphics {
    "foo"("bar")
    "bar" of "baz"
    -"goo"
    +"doo"
}
```
