### ISSUE TITLE
Как используется vararg в \usepackage?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#66]
В примере команда `\usepackage[russian]{babel}` кодируется так:

```
usepackage("russian", "babel" /* varargs */)
```

Кажется странным делать vararg'ом именно список пакетов. Параметр `russian` - это что-то специфичное для babel. С другой стороны, сделать vararg'ом параметры в текущем синтаксисе не получается, потому что после них могут идти только именованные параметры.

@dzharkov

**Comment by dzharkov** [comment]
Да, я перепутал. Должно быть `usepackage("babel", "russian" /* varargs */)`
