### ISSUE TITLE
Требуется ли pretty printing для задания на TeX или достаточно просто вывести текст?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#67]
@dzharkov 

Больше всего интересуют отступы.

**Comment by dzharkov** [comment]
Ну да, было бы неплохо, если бы сгенеренный тех был бы человекочитаем

**Comment by yeputons** [comment]
@dzharkov "Неплохо" или "требуется для получения баллов"? Скажем, можно сгенерировать просто по команде на строку, но без отступов — это, мне кажется, проще, чем генерировать ещё и отступы и как-то их внутрь классов протаскивать.
