### ISSUE TITLE
Какова семантика разбития на параграфы?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#68]
В техе параграфы отделяются друг от друга пустой строкой. В примере нет никаких намёков на то, как это можно сделать. Я потенциально вижу три семантики:

1. Команда `+"foo"` просто дописывает строчку в конец. То есть `+"foo"; +"bar"` допишет `foobar`.
2. Каждая команда `+"foo"` заводит себе отдельную строку в выходном файле. То есть `+"foo"; +"bar"` допишет `foo\nbar". Можно дополнительно завести команду `newParagraph()`, которая выводит пустую строку для разделения.
3. Каждая команда `+"foo"` заводит себе отдельный параграф в выходном файле.

@dzharkov 

Мне больше всего нравится вариант 2.

**Comment by dzharkov** [comment]
Тоже дизайнерский вопрос, я не против второго варианта
