### ISSUE TITLE
Что делает тэг/команда math?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#69]
Я не знаю команду `\begin{math}` в техе или похожую. Пример ввода/вывода бы пригодился.

@dzharkov

**Comment by dzharkov** [comment]
Это про `$$`. Должна быть возможность хотя бы текстом вставлять формулы

**Comment by yeputons** [comment]
@dzharkov 
`$$` (выключная формула, появляется на отдельной строке, в LaTeX зовётся `\[` и `\]`) или `$` (формула прямо внутри текста)?

**Comment by dzharkov** [comment]
Как тебе покажется будет лучше.
Еще раз повторюсь: это задание, где как раз и нужно подумать, как лучше сделать. 
С другой стороны, вряд ли претензии при проверке будут по поводу того, какая из этих двух опций будет выбрана
