### ISSUE TITLE
Верно ли, что унарный `+` вызывает `trimMargin` на всех своих аргументах?

### ISSUE THREAD

**Issue by yeputons** [java-course-au/kotlin-course#71]
@dzharkov 

Если да, то мне это кажется хорошими потенциальными граблями, на которые может наступить пользователь. Например, если захотел продемонстрировать, как вставляется ровно такой код с margin'ом.

**Comment by dzharkov** [comment]
Это вопрос к дизайнеру DSL, то есть к вам.
Я по этому поводу придираться не планирую
